from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


# ---------------------------------------------------------
# Phase 1: Drug Input & Molecular Evidence Schemas
# ---------------------------------------------------------

class DrugSmilesInput(BaseModel):
    """Request body for SMILES-based drug analysis."""
    smiles: str = Field(
        ...,
        min_length=1,
        description="Drug molecule represented as a SMILES string.",
        examples=["CC(=O)NC1=CC=C(O)C=C1"],
    )
    drug_id: Optional[str] = Field(
        default=None,
        description="Optional drug identifier (e.g., CHEMBL ID, DrugBank ID, or internal code).",
        examples=["CHEMBL112"],
    )
    name: Optional[str] = Field(
        default=None,
        description="Optional common or brand name for the compound.",
        examples=["Acetaminophen"],
    )


class DrugInputMetadata(BaseModel):
    """Metadata describing the input source and identifiers."""
    drug_id: Optional[str] = Field(default=None, description="Drug or compound identifier")
    name: Optional[str] = Field(default=None, description="Common name of the compound")
    input_type: str = Field(..., description="Format of the input provided ('smiles', 'sdf', 'mol')")
    input_value: Optional[str] = Field(default=None, description="Raw input text or uploaded filename")


class MoleculeIdentifiers(BaseModel):
    """Standardized chemical identifiers and formula properties."""
    canonical_smiles: str = Field(..., description="Canonical SMILES representation generated by RDKit")
    inchi: Optional[str] = Field(default=None, description="IUPAC International Chemical Identifier (InChI)")
    inchi_key: Optional[str] = Field(default=None, description="Standard 27-character hashed InChIKey")
    formula: Optional[str] = Field(default=None, description="Hill system molecular formula (e.g. C8H9NO2)")
    num_atoms: int = Field(..., description="Total atom count (including implicit and explicit hydrogens)")
    num_heavy_atoms: int = Field(..., description="Total count of non-hydrogen heavy atoms")


class MolecularDescriptors(BaseModel):
    """Calculated 2D/3D physicochemical molecular descriptors."""
    molecular_weight: float = Field(..., description="Molecular weight (g/mol)")
    logp: float = Field(..., description="Wildman-Crippen calculated partition coefficient (LogP)")
    tpsa: float = Field(..., description="Topological Polar Surface Area (Å²)")
    hbd: int = Field(..., description="Number of Hydrogen Bond Donors (Lipinski rule)")
    hba: int = Field(..., description="Number of Hydrogen Bond Acceptors (Lipinski rule)")
    rotatable_bonds: int = Field(..., description="Number of rotatable single bonds")
    heavy_atom_count: int = Field(..., description="Total heavy (non-H) atoms")
    ring_count: int = Field(..., description="Total number of rings")
    aromatic_ring_count: int = Field(..., description="Total number of aromatic rings")


class FingerprintData(BaseModel):
    """Morgan circular fingerprint representation."""
    type: str = Field(default="Morgan", description="Fingerprint algorithm type")
    radius: int = Field(default=2, description="Morgan circular radius (equivalent to ECFP4)")
    size: int = Field(default=2048, description="Bit vector length")
    active_bits: int = Field(..., description="Count of active (1) bits")
    bits: List[int] = Field(..., description="2048-element bit vector (0/1 values)")


class ProcessingStatus(BaseModel):
    """Processing health and validation status."""
    valid: bool = Field(default=True, description="Whether the molecular structure is chemically valid")
    message: str = Field(
        default="Molecular evidence extracted successfully.",
        description="Informative status message",
    )


class MolecularProcessingResponse(BaseModel):
    """Standard Phase 1 Molecular Evidence Response."""
    drug: DrugInputMetadata
    molecule: MoleculeIdentifiers
    descriptors: MolecularDescriptors
    fingerprint: FingerprintData
    status: ProcessingStatus

    # Top-level backward compatibility convenience fields
    valid: bool
    canonical_smiles: str
    input_smiles: Optional[str] = None
    fingerprint_size: int
    active_fingerprint_bits: int
    filename: Optional[str] = None
    svg_image: Optional[str] = None


class DemoDrugItem(BaseModel):
    """Demo compound pre-loaded for quick evaluation."""
    name: str
    smiles: str
    chembl_id: Optional[str] = None
    description: Optional[str] = None


class HealthResponse(BaseModel):
    """API health check response."""
    status: str = "ok"
    app_name: str
    version: str
    environment: str


# ---------------------------------------------------------
# Phase 2: Normalized Biomedical Evidence Schemas
# ---------------------------------------------------------

EntityType = Literal[
    "drug",
    "target",
    "protein",
    "gene",
    "pathway",
    "tissue",
    "organ",
    "adverse_effect",
    "disease",
    "paper",
]


class NormalizedEvidence(BaseModel):
    """
    Standardized, atomic biomedical evidence record linking entities
    with confidence scores and complete provenance.
    """
    source: str = Field(..., description="Biomedical source provider", examples=["ChEMBL"])
    entity_type: EntityType = Field(..., description="Standardized entity classification", examples=["target"])
    entity_id: str = Field(..., description="Standardized CURIE or identifier", examples=["CHEMBL:CHEMBL221"])
    entity_name: str = Field(..., description="Canonical entity name", examples=["PTGS1 / COX-1"])
    relation: str = Field(..., description="Semantic relationship verb", examples=["inhibits"])
    object_id: str = Field(..., description="Identifier of the subject/drug object", examples=["CHEMBL:CHEMBL112"])
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Confidence score (0.0 to 1.0)")
    evidence_type: str = Field(..., description="Methodological category", examples=["bioassay"])
    retrieved_at: str = Field(..., description="ISO 8601 UTC timestamp of retrieval")
    source_version: Optional[str] = Field(default=None, description="Version of source database")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Contextual metadata")


class EvidenceSummary(BaseModel):
    """Summary statistics for aggregated multi-source biomedical evidence."""
    total_evidence_count: int
    sources_contacted: List[str]
    sources_succeeded: List[str]
    sources_failed: List[str] = Field(default_factory=list)
    entity_type_counts: Dict[str, int] = Field(default_factory=dict)
    target_count: int = 0
    adverse_effect_count: int = 0
    pathway_count: int = 0
    literature_count: int = 0


class DrugEvidenceQuery(BaseModel):
    """Request payload for biomedical evidence query."""
    drug_id: Optional[str] = Field(default=None, description="Drug identifier (e.g. CHEMBL112)")
    smiles: Optional[str] = Field(default=None, description="SMILES string")
    name: Optional[str] = Field(default=None, description="Common drug name")
    force_refresh: bool = Field(default=False, description="Bypass local cache")


class DrugEvidenceResponse(BaseModel):
    """Complete aggregated response for Phase 2 evidence ingestion."""
    drug_id: str
    drug_name: Optional[str] = None
    canonical_smiles: Optional[str] = None
    cached: bool = False
    demo_mode: bool = True
    summary: EvidenceSummary
    evidence: List[NormalizedEvidence]
    status: ProcessingStatus


# ---------------------------------------------------------
# Phase 3: Biomedical Knowledge Graph Schemas
# ---------------------------------------------------------

class GraphNodeModel(BaseModel):
    """Knowledge graph node representing a biomedical entity."""
    id: str = Field(..., description="Unique standardized CURIE identifier (e.g., CHEMBL:CHEMBL112, ORGAN:LIVER)")
    name: str = Field(..., description="Human-readable label or entity name")
    type: str = Field(..., description="Entity classification type (Drug, Target, Protein, Gene, Pathway, Tissue, Organ, AdverseEffect, Disease, Literature)")
    properties: Dict[str, Any] = Field(default_factory=dict, description="Associated attributes and descriptors")


class GraphEdgeModel(BaseModel):
    """Knowledge graph edge representing a directed biomedical relation."""
    id: str = Field(..., description="Unique edge identifier")
    source: str = Field(..., description="Source node CURIE identifier")
    target: str = Field(..., description="Target node CURIE identifier")
    relation: str = Field(..., description="Relationship semantic verb (TARGETS, INHIBITS, ENCODED_BY, PARTICIPATES_IN, AFFECTS_ORGAN, etc.)")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Evidence confidence score (0.0 to 1.0)")
    source_db: str = Field(default="KnowledgeGraph", description="Originating database source")
    evidence_type: str = Field(default="curated_graph", description="Type of evidence supporting relation")
    provenance_id: Optional[str] = Field(default=None, description="Reference provenance ID or PMID")
    retrieved_at: Optional[str] = Field(default=None, description="ISO timestamp")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Detailed assay or mechanism parameters")


class GraphPathModel(BaseModel):
    """Traceable reasoning path from drug to organ or adverse event."""
    path_id: str = Field(..., description="Unique path identifier")
    path_type: str = Field(..., description="Path category ('mechanistic_organ_path', 'adverse_phenotype_path', 'pathway_association')")
    target_organ: Optional[str] = Field(default=None, description="Terminal organ entity if applicable")
    nodes: List[str] = Field(..., description="Ordered list of node IDs along the path")
    node_names: List[str] = Field(..., description="Ordered list of human-readable node names")
    relations: List[str] = Field(..., description="Ordered list of relationship types connecting the nodes")
    confidence: float = Field(..., description="Aggregated multi-hop confidence score (0.0 to 1.0)")
    confidence_tier: str = Field(..., description="'high' (>=0.75), 'moderate' (0.50-0.74), or 'low' (<0.50)")
    description: str = Field(..., description="Human-readable natural language summary of the path")


class GraphSubgraphResponse(BaseModel):
    """Complete frontend-ready knowledge graph response."""
    drug_id: str
    drug_name: Optional[str] = None
    canonical_smiles: Optional[str] = None
    engine: str = Field(default="InMemoryGraph", description="Graph engine utilized ('InMemoryGraph' or 'Neo4j')")
    total_nodes: int
    total_edges: int
    nodes: List[GraphNodeModel]
    edges: List[GraphEdgeModel]
    paths: List[GraphPathModel]
    evidence_sources: List[str]
    status: ProcessingStatus


class GraphPathsResponse(BaseModel):
    """Reasoning paths extracted from knowledge graph."""
    drug_id: str
    drug_name: Optional[str] = None
    total_paths: int
    paths: List[GraphPathModel]
    status: ProcessingStatus


class GraphSearchResultItem(BaseModel):
    """Single node result for graph search."""
    id: str
    name: str
    type: str
    degree: int
    properties: Dict[str, Any] = Field(default_factory=dict)


class GraphSearchResponse(BaseModel):
    """Graph search query results."""
    query: str
    entity_type: Optional[str] = None
    total_results: int
    results: List[GraphSearchResultItem]
    status: ProcessingStatus
