from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


# ---------------------------------------------------------
# Phase 1: Drug Input & Molecular Evidence Schemas
# ---------------------------------------------------------

class DrugSmilesInput(BaseModel):
    """Request body for SMILES-based drug analysis."""
    smiles: str = Field(
        ...,
        min_length=1,
        description="Drug molecule represented as a SMILES string.",
        examples=["CC(=O)NC1=CC=C(O)C=C1"],
    )
    drug_id: Optional[str] = Field(
        default=None,
        description="Optional drug identifier (e.g., CHEMBL ID, DrugBank ID, or internal code).",
        examples=["CHEMBL112"],
    )
    name: Optional[str] = Field(
        default=None,
        description="Optional common or brand name for the compound.",
        examples=["Acetaminophen"],
    )


class DrugInputMetadata(BaseModel):
    """Metadata describing the input source and identifiers."""
    drug_id: Optional[str] = Field(default=None, description="Drug or compound identifier")
    name: Optional[str] = Field(default=None, description="Common name of the compound")
    input_type: str = Field(..., description="Format of the input provided ('smiles', 'sdf', 'mol')")
    input_value: Optional[str] = Field(default=None, description="Raw input text or uploaded filename")


class MoleculeIdentifiers(BaseModel):
    """Standardized chemical identifiers and formula properties."""
    canonical_smiles: str = Field(..., description="Canonical SMILES representation generated by RDKit")
    inchi: Optional[str] = Field(default=None, description="IUPAC International Chemical Identifier (InChI)")
    inchi_key: Optional[str] = Field(default=None, description="Standard 27-character hashed InChIKey")
    formula: Optional[str] = Field(default=None, description="Hill system molecular formula (e.g. C8H9NO2)")
    num_atoms: int = Field(..., description="Total atom count (including implicit and explicit hydrogens)")
    num_heavy_atoms: int = Field(..., description="Total count of non-hydrogen heavy atoms")


class MolecularDescriptors(BaseModel):
    """Calculated 2D/3D physicochemical molecular descriptors."""
    molecular_weight: float = Field(..., description="Molecular weight (g/mol)")
    logp: float = Field(..., description="Wildman-Crippen calculated partition coefficient (LogP)")
    tpsa: float = Field(..., description="Topological Polar Surface Area (Å²)")
    hbd: int = Field(..., description="Number of Hydrogen Bond Donors (Lipinski rule)")
    hba: int = Field(..., description="Number of Hydrogen Bond Acceptors (Lipinski rule)")
    rotatable_bonds: int = Field(..., description="Number of rotatable single bonds")
    heavy_atom_count: int = Field(..., description="Total heavy (non-H) atoms")
    ring_count: int = Field(..., description="Total number of rings")
    aromatic_ring_count: int = Field(..., description="Total number of aromatic rings")


class FingerprintData(BaseModel):
    """Morgan circular fingerprint representation."""
    type: str = Field(default="Morgan", description="Fingerprint algorithm type")
    radius: int = Field(default=2, description="Morgan circular radius (equivalent to ECFP4)")
    size: int = Field(default=2048, description="Bit vector length")
    active_bits: int = Field(..., description="Count of active (1) bits")
    bits: List[int] = Field(..., description="2048-element bit vector (0/1 values)")


class ProcessingStatus(BaseModel):
    """Processing health and validation status."""
    valid: bool = Field(default=True, description="Whether the molecular structure is chemically valid")
    message: str = Field(
        default="Molecular evidence extracted successfully.",
        description="Informative status message",
    )


class MolecularProcessingResponse(BaseModel):
    """Standard Phase 1 Molecular Evidence Response."""
    drug: DrugInputMetadata
    molecule: MoleculeIdentifiers
    descriptors: MolecularDescriptors
    fingerprint: FingerprintData
    status: ProcessingStatus

    # Top-level backward compatibility convenience fields
    valid: bool
    canonical_smiles: str
    input_smiles: Optional[str] = None
    fingerprint_size: int
    active_fingerprint_bits: int
    filename: Optional[str] = None
    svg_image: Optional[str] = None


class DemoDrugItem(BaseModel):
    """Demo compound pre-loaded for quick evaluation."""
    name: str
    smiles: str
    chembl_id: Optional[str] = None
    description: Optional[str] = None


class HealthResponse(BaseModel):
    """API health check response."""
    status: str = "ok"
    app_name: str
    version: str
    environment: str


# ---------------------------------------------------------
# Phase 2: Normalized Biomedical Evidence Schemas
# ---------------------------------------------------------

EntityType = Literal[
    "drug",
    "target",
    "protein",
    "gene",
    "pathway",
    "tissue",
    "organ",
    "adverse_effect",
    "disease",
    "paper",
]


class NormalizedEvidence(BaseModel):
    """
    Standardized, atomic biomedical evidence record linking entities
    with confidence scores and complete provenance.
    """
    source: str = Field(..., description="Biomedical source provider", examples=["ChEMBL"])
    entity_type: EntityType = Field(..., description="Standardized entity classification", examples=["target"])
    entity_id: str = Field(..., description="Standardized CURIE or identifier", examples=["CHEMBL:CHEMBL221"])
    entity_name: str = Field(..., description="Canonical entity name", examples=["PTGS1 / COX-1"])
    relation: str = Field(..., description="Semantic relationship verb", examples=["inhibits"])
    object_id: str = Field(..., description="Identifier of the subject/drug object", examples=["CHEMBL:CHEMBL112"])
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Confidence score (0.0 to 1.0)")
    evidence_type: str = Field(..., description="Methodological category", examples=["bioassay"])
    retrieved_at: str = Field(..., description="ISO 8601 UTC timestamp of retrieval")
    source_version: Optional[str] = Field(default=None, description="Version of source database")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Contextual metadata")


class EvidenceSummary(BaseModel):
    """Summary statistics for aggregated multi-source biomedical evidence."""
    total_evidence_count: int
    sources_contacted: List[str]
    sources_succeeded: List[str]
    sources_failed: List[str] = Field(default_factory=list)
    entity_type_counts: Dict[str, int] = Field(default_factory=dict)
    target_count: int = 0
    adverse_effect_count: int = 0
    pathway_count: int = 0
    literature_count: int = 0


class DrugEvidenceQuery(BaseModel):
    """Request payload for biomedical evidence query."""
    drug_id: Optional[str] = Field(default=None, description="Drug identifier (e.g. CHEMBL112)")
    smiles: Optional[str] = Field(default=None, description="SMILES string")
    name: Optional[str] = Field(default=None, description="Common drug name")
    force_refresh: bool = Field(default=False, description="Bypass local cache")


class DrugEvidenceResponse(BaseModel):
    """Complete aggregated response for Phase 2 evidence ingestion."""
    drug_id: str
    drug_name: Optional[str] = None
    canonical_smiles: Optional[str] = None
    cached: bool = False
    demo_mode: bool = True
    summary: EvidenceSummary
    evidence: List[NormalizedEvidence]
    status: ProcessingStatus


# ---------------------------------------------------------
# Phase 3: Biomedical Knowledge Graph Schemas
# ---------------------------------------------------------

class GraphNodeModel(BaseModel):
    """Knowledge graph node representing a biomedical entity."""
    id: str = Field(..., description="Unique standardized CURIE identifier (e.g., CHEMBL:CHEMBL112, ORGAN:LIVER)")
    name: str = Field(..., description="Human-readable label or entity name")
    type: str = Field(..., description="Entity classification type (Drug, Target, Protein, Gene, Pathway, Tissue, Organ, AdverseEffect, Disease, Literature)")
    properties: Dict[str, Any] = Field(default_factory=dict, description="Associated attributes and descriptors")


class GraphEdgeModel(BaseModel):
    """Knowledge graph edge representing a directed biomedical relation."""
    id: str = Field(..., description="Unique edge identifier")
    source: str = Field(..., description="Source node CURIE identifier")
    target: str = Field(..., description="Target node CURIE identifier")
    relation: str = Field(..., description="Relationship semantic verb (TARGETS, INHIBITS, ENCODED_BY, PARTICIPATES_IN, AFFECTS_ORGAN, etc.)")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Evidence confidence score (0.0 to 1.0)")
    source_db: str = Field(default="KnowledgeGraph", description="Originating database source")
    evidence_type: str = Field(default="curated_graph", description="Type of evidence supporting relation")
    provenance_id: Optional[str] = Field(default=None, description="Reference provenance ID or PMID")
    retrieved_at: Optional[str] = Field(default=None, description="ISO timestamp")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Detailed assay or mechanism parameters")


class GraphPathModel(BaseModel):
    """Traceable reasoning path from drug to organ or adverse event."""
    path_id: str = Field(..., description="Unique path identifier")
    path_type: str = Field(..., description="Path category ('mechanistic_organ_path', 'adverse_phenotype_path', 'pathway_association')")
    target_organ: Optional[str] = Field(default=None, description="Terminal organ entity if applicable")
    nodes: List[str] = Field(..., description="Ordered list of node IDs along the path")
    node_names: List[str] = Field(..., description="Ordered list of human-readable node names")
    relations: List[str] = Field(..., description="Ordered list of relationship types connecting the nodes")
    confidence: float = Field(..., description="Aggregated multi-hop confidence score (0.0 to 1.0)")
    confidence_tier: str = Field(..., description="'high' (>=0.75), 'moderate' (0.50-0.74), or 'low' (<0.50)")
    description: str = Field(..., description="Human-readable natural language summary of the path")


class GraphSubgraphResponse(BaseModel):
    """Complete frontend-ready knowledge graph response."""
    drug_id: str
    drug_name: Optional[str] = None
    canonical_smiles: Optional[str] = None
    engine: str = Field(default="InMemoryGraph", description="Graph engine utilized ('InMemoryGraph' or 'Neo4j')")
    total_nodes: int
    total_edges: int
    nodes: List[GraphNodeModel]
    edges: List[GraphEdgeModel]
    paths: List[GraphPathModel]
    evidence_sources: List[str]
    status: ProcessingStatus


class GraphPathsResponse(BaseModel):
    """Reasoning paths extracted from knowledge graph."""
    drug_id: str
    drug_name: Optional[str] = None
    total_paths: int
    paths: List[GraphPathModel]
    status: ProcessingStatus


class GraphSearchResultItem(BaseModel):
    """Single node result for graph search."""
    id: str
    name: str
    type: str
    degree: int
    properties: Dict[str, Any] = Field(default_factory=dict)


class GraphSearchResponse(BaseModel):
    """Graph search query results."""
    query: str
    entity_type: Optional[str] = None
    total_results: int
    results: List[GraphSearchResultItem]
    status: ProcessingStatus


# ---------------------------------------------------------
# Phase 4: Evidence Fusion & Risk Reasoning Schemas
# ---------------------------------------------------------

class OrganRiskAssessment(BaseModel):
    """Decomposed risk prediction and evidence summary for a single organ system."""
    organ: str = Field(..., description="Organ key: 'heart', 'liver', 'kidney', 'lung', 'brain'")
    organ_name: str = Field(..., description="Full descriptive anatomical organ name")
    risk_score: float = Field(..., ge=0.0, le=1.0, description="Predicted risk probability score (0.0 to 1.0)")
    risk_category: str = Field(..., description="Prototype category: 'Low' (<0.35), 'Moderate' (0.35-0.69), 'High' (>=0.70)")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Model and evidence confidence estimate (0.0 to 1.0)")
    evidence_strength: float = Field(..., ge=0.0, le=1.0, description="Normalized multi-source evidence volume & consistency score")
    primary_mechanisms: List[str] = Field(default_factory=list, description="Mechanistic pathways or known pharmacological risks")
    graph_paths_count: int = Field(default=0, description="Number of multi-hop knowledge graph paths to this organ")
    adverse_effects_count: int = Field(default=0, description="Number of recorded clinical adverse reactions on this organ")
    literature_citations_count: int = Field(default=0, description="Number of literature citations supporting this organ endpoint")


class EvidenceSufficiencyCheck(BaseModel):
    """Evidence sufficiency gating evaluation."""
    is_sufficient: bool = Field(..., description="True if evidence meets sufficiency criteria across sources")
    flag_for_review: bool = Field(..., description="True if evidence is sparse or insufficient, requiring manual/expert review")
    review_reasons: List[str] = Field(default_factory=list, description="Explicit reasons for flagging if evidence is insufficient")
    criteria_met: Dict[str, bool] = Field(default_factory=dict, description="Checklist of evaluated evidence gates")


class MolecularSimilarityMatch(BaseModel):
    """Tanimoto similarity evidence against benchmark drugs."""
    reference_drug_id: str = Field(..., description="Benchmark compound ID (e.g. CHEMBL112)")
    reference_drug_name: str = Field(..., description="Benchmark compound name")
    tanimoto_similarity: float = Field(..., ge=0.0, le=1.0, description="Tanimoto similarity coefficient over Morgan fingerprints")
    known_organ_risks: List[str] = Field(default_factory=list, description="Established organ toxicities of the benchmark drug")
    disclaimer: str = Field(
        default="Molecular similarity informs prior evidence retrieval, but does not prove clinical toxicity.",
        description="Scientific scope disclaimer",
    )


class RiskExplainabilityMetadata(BaseModel):
    """Comprehensive explainability payload supporting the prediction."""
    contributing_features: List[Dict[str, Any]] = Field(default_factory=list, description="Top ranked physicochemical & fingerprint features")
    contributing_evidence: List[NormalizedEvidence] = Field(default_factory=list, description="Supporting multi-source evidence records")
    graph_paths: List[GraphPathModel] = Field(default_factory=list, description="Supporting multi-hop reasoning paths")
    literature_references: List[Dict[str, Any]] = Field(default_factory=list, description="Supporting peer-reviewed literature records")
    similarity_matches: List[MolecularSimilarityMatch] = Field(default_factory=list, description="Nearest benchmark compounds by Morgan fingerprint similarity")


class DrugRiskPredictionRequest(BaseModel):
    """Request payload for risk reasoning and multi-organ prediction."""
    drug_id: Optional[str] = Field(default=None, description="Optional drug identifier (e.g. CHEMBL112)")
    smiles: Optional[str] = Field(default=None, description="SMILES representation of the query molecule")
    name: Optional[str] = Field(default=None, description="Optional common compound name")
    model_type: Optional[str] = Field(
        default="random_forest",
        description="Risk model architecture: 'random_forest', 'logistic_regression', or 'ensemble'",
    )


class DrugRiskPredictionResponse(BaseModel):
    """
    Standard Phase 4 Multi-Modal Risk Reasoning & Organ Prediction Response.
    Strictly separates model prediction, confidence, evidence strength, and prototype tiers.
    """
    prediction_id: str = Field(..., description="Unique UUID for this prediction run")
    drug_id: str = Field(..., description="Evaluated drug identifier")
    drug_name: Optional[str] = Field(default=None, description="Evaluated compound name")
    canonical_smiles: Optional[str] = Field(default=None, description="Canonical SMILES structure")
    model_used: str = Field(..., description="Machine learning model architecture used for inference")
    overall_risk: float = Field(..., ge=0.0, le=1.0, description="Predicted overall adverse risk probability score (0.0 to 1.0)")
    overall_risk_category: str = Field(..., description="Prototype category: 'Low', 'Moderate', 'High'")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Prediction certainty score based on evidence coverage and model confidence")
    evidence_strength: float = Field(..., ge=0.0, le=1.0, description="Aggregate volume, diversity, and consistency of supporting evidence")
    organ_risks: Dict[str, OrganRiskAssessment] = Field(..., description="Decomposed organ-level risk predictions for heart, liver, kidney, lung, brain")
    evidence_sufficiency: EvidenceSufficiencyCheck = Field(..., description="Sufficiency gating results and review flags")
    explainability: RiskExplainabilityMetadata = Field(..., description="Traceable feature attributions, graph paths, and evidence records")
    disclaimer: str = Field(
        default="Research-grade decision-support prototype. Categories are prototype thresholds, not clinically validated diagnostic conclusions.",
        description="Mandatory research boundary disclaimer",
    )
    status: ProcessingStatus = Field(..., description="Execution status")
    created_at: str = Field(..., description="ISO 8601 UTC timestamp of prediction generation")


# ---------------------------------------------------------
# Phase 5: Explainability & Evidence Traceability Schemas
# ---------------------------------------------------------

class FeatureSHAPExplanation(BaseModel):
    """Local SHAP feature attribution record for a single feature dimension."""
    feature_name: str = Field(..., description="Standardized feature identifier")
    feature_value: float = Field(..., description="Observed input value for this instance")
    contribution: float = Field(..., description="SHAP value (additive shift from base value to prediction)")
    direction: str = Field(..., description="'increases_risk' if contribution > 0 else 'decreases_risk'")
    rank: int = Field(..., description="Importance rank ordered by absolute contribution magnitude")
    description: str = Field(..., description="Human-readable pharmacological/computational explanation of the feature")
    attribution_type: str = Field(
        default="statistical_feature_contribution",
        description="Type of attribution: 'statistical_feature_contribution' (SHAP) vs 'mechanistic_biological_pathway'",
    )


class ExplanationQualityMetadata(BaseModel):
    """Quality and provenance metadata for the explainability report."""
    evidence_count: int = Field(..., description="Total count of supporting evidence items")
    evidence_source_diversity: List[str] = Field(..., description="Distinct upstream databases contributing evidence")
    confidence: float = Field(..., description="Prediction confidence score")
    evidence_sufficiency: EvidenceSufficiencyCheck = Field(..., description="Sufficiency check evaluation")
    base_value: float = Field(..., description="Expected value E[f(x)] across background baseline dataset")
    prediction_value: float = Field(..., description="Model prediction probability f(x)")


class PredictionExplanationResponse(BaseModel):
    """
    Standard Phase 5 UI-Ready Explainability & Evidence Traceability Response.
    Answers: 'WHY DID PHARMATWIN PREDICT THIS RISK?'
    Strictly separates statistical feature attribution from biological causality.
    """
    prediction_id: str = Field(..., description="Unique prediction UUID")
    drug_id: str = Field(..., description="Evaluated drug identifier")
    drug_name: Optional[str] = Field(default=None, description="Common compound name")
    canonical_smiles: Optional[str] = Field(default=None, description="Canonical SMILES representation")
    model_used: str = Field(..., description="Model architecture used for inference")
    overall_risk: float = Field(..., ge=0.0, le=1.0, description="Predicted overall adverse risk probability")
    overall_risk_category: str = Field(..., description="Prototype category: 'Low', 'Moderate', 'High'")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Prediction certainty score")
    evidence_strength: float = Field(..., ge=0.0, le=1.0, description="Evidence volume and diversity score")
    base_value: float = Field(..., description="Baseline expected prediction E[f(x)]")
    top_features: List[FeatureSHAPExplanation] = Field(default_factory=list, description="Top ranked SHAP feature attributions")
    all_feature_contributions: List[FeatureSHAPExplanation] = Field(default_factory=list, description="Complete 32-dim SHAP attribution array")
    supporting_paths: List[GraphPathModel] = Field(default_factory=list, description="Traceable mechanistic paths in knowledge graph")
    supporting_evidence: List[NormalizedEvidence] = Field(default_factory=list, description="Supporting multi-source evidence records")
    supporting_literature: List[Dict[str, Any]] = Field(default_factory=list, description="Supporting peer-reviewed literature records")
    similarity_matches: List[MolecularSimilarityMatch] = Field(default_factory=list, description="Benchmark compound similarity matches")
    quality_metadata: ExplanationQualityMetadata = Field(..., description="Explanation quality, diversity, and sufficiency metrics")
    causality_distinction: str = Field(
        default=(
            "Statistical feature attributions (SHAP) quantify how input variables shifted the statistical model "
            "score relative to the background baseline. They do NOT constitute proven biological causality. "
            "Traceable biological hypotheses are represented separately via Knowledge Graph mechanistic paths."
        ),
        description="Explicit boundary distinguishing statistical feature contribution from biological causality",
    )
    disclaimer: str = Field(
        default=(
            "Research-grade decision-support prototype. Predictions and feature attributions are computational "
            "hypotheses and must be experimentally validated. Not a clinical diagnostic or treatment recommendation system."
        ),
        description="Mandatory scientific boundary disclaimer",
    )
    created_at: str = Field(..., description="ISO 8601 UTC timestamp")


# ---------------------------------------------------------
# Phase 6: Organ Risk Mapping Schemas
# ---------------------------------------------------------

class OrganDetailRiskModel(BaseModel):
    """Rich organ-level risk assessment and evidence aggregation for 3D Virtual Twin."""
    organ_id: str = Field(..., description="Standardized organ key (e.g. 'heart', 'liver', 'kidney', 'gastrointestinal')")
    name: str = Field(..., description="Human-readable organ name (e.g. 'Heart', 'Liver')")
    system: str = Field(..., description="Physiological organ system (e.g. 'Cardiovascular System', 'Hepatic System')")
    anatomical_region: str = Field(..., description="Anatomical location/cavity for 3D viewport rendering")
    risk: float = Field(..., ge=0.0, le=1.0, description="Predicted risk probability score (0.0 to 1.0)")
    category: str = Field(..., description="Prototype category: 'Low', 'Moderate', 'High'")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence certainty score (0.0 to 1.0)")
    evidence_strength: str = Field(..., description="Evidence volume tier: 'Low', 'Medium', 'High'")
    evidence_strength_score: float = Field(..., ge=0.0, le=1.0, description="Normalized continuous evidence strength")
    evidence_count: int = Field(..., description="Total count of supporting evidence records and paths")
    primary_mechanisms: List[str] = Field(default_factory=list, description="Mechanistic pathways or known pharmacological risks")
    paths: List[GraphPathModel] = Field(default_factory=list, description="Traceable Knowledge Graph paths terminating in this organ")
    adverse_effects: List[Dict[str, Any]] = Field(default_factory=list, description="Clinical SIDER adverse reactions mapped to this organ")
    literature_citations: List[Dict[str, Any]] = Field(default_factory=list, description="Peer-reviewed literature records supporting this organ toxicity")


class OrganRiskMappingResponse(BaseModel):
    """
    Standard Phase 6 Organ Risk Mapping Response.
    Structures multi-modal evidence and risk predictions into physiological organ systems.
    """
    prediction_id: str = Field(..., description="Unique prediction UUID")
    drug_id: str = Field(..., description="Evaluated drug identifier")
    drug_name: Optional[str] = Field(default=None, description="Compound name")
    canonical_smiles: Optional[str] = Field(default=None, description="Canonical SMILES representation")
    highest_risk_organ: str = Field(..., description="Organ key with highest predicted toxicity risk")
    overall_risk_score: float = Field(..., ge=0.0, le=1.0, description="Predicted overall adverse risk score")
    overall_risk_category: str = Field(..., description="Overall risk prototype tier: 'Low', 'Moderate', 'High'")
    organs: Dict[str, OrganDetailRiskModel] = Field(..., description="Organ-level risk mappings across supported systems")
    supported_organs: List[str] = Field(default_factory=list, description="List of all supported anatomical organ keys")
    evidence_sufficiency: EvidenceSufficiencyCheck = Field(..., description="Evidence sufficiency check results")
    disclaimer: str = Field(
        default=(
            "Research-grade prototype. Organ risk mapping represents potential risk signals derived from "
            "computational models and biomedical evidence fusion. It is not a clinical diagnosis or treatment recommendation."
        ),
        description="Scientific scope disclaimer",
    )
    created_at: str = Field(..., description="ISO 8601 UTC timestamp")


# ---------------------------------------------------------
# Phase 9: Persistent Storage & Auditability Schemas
# ---------------------------------------------------------

class AuditEventModel(BaseModel):
    """Immutable audit log event record."""
    event_id: str = Field(..., description="Unique audit event UUID")
    timestamp: str = Field(..., description="ISO 8601 UTC timestamp of event occurrence")
    user_session: str = Field(..., description="User identifier or system execution context")
    action: str = Field(..., description="Audited operation: DRUG_PROCESSED, PREDICTION_CREATED, etc.")
    object_type: str = Field(..., description="Entity class: Drug, Molecule, Prediction, etc.")
    object_id: str = Field(..., description="Target entity primary identifier")
    model_version: Optional[str] = Field(default=None, description="Active model version during execution")
    status: str = Field(..., description="Execution outcome: SUCCESS, FAILED, GATED")
    details: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Structured contextual event payload")


class ModelVersionModel(BaseModel):
    """Registered machine learning model version and metadata record."""
    id: str = Field(..., description="Unique model version record ID")
    model_name: str = Field(..., description="Human-readable model name")
    model_version: str = Field(..., description="Unique version tag (e.g. v1.0.0-rf-calibrated)")
    feature_version: str = Field(..., description="Input feature schema version (e.g. v1.0.0-multi-modal-32d)")
    training_dataset_version: str = Field(..., description="Training dataset version tag")
    hyperparameters: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Model hyperparameter configuration")
    metrics_summary: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Summary validation metrics")
    is_active: bool = Field(default=True, description="Whether this version is active for inference")
    created_at: str = Field(..., description="ISO 8601 UTC timestamp")


class AuditTrailResponse(BaseModel):
    """Complete traceable lineage and audit trail for a prediction."""
    prediction_id: str = Field(..., description="Target prediction UUID")
    drug_id: str = Field(..., description="Evaluated drug identifier")
    model_name: str = Field(..., description="Model architecture used")
    model_version: str = Field(..., description="Model version tag")
    feature_version: str = Field(..., description="Feature schema version")
    training_dataset_version: str = Field(..., description="Training dataset version")
    created_at: str = Field(..., description="ISO 8601 UTC timestamp")
    reproducible_chain: List[str] = Field(default_factory=list, description="Ordered pipeline execution milestones")
    lineage: Dict[str, Any] = Field(..., description="Nested snapshots of Drug, Molecule, Evidence, Graph, Prediction, and Organs")
    audit_trail: List[AuditEventModel] = Field(default_factory=list, description="Historical audit events linked to this prediction")


# ---------------------------------------------------------
# Phase 10: Model Validation & Research Evaluation Schemas
# ---------------------------------------------------------

class EvaluationDatasetMetadata(BaseModel):
    """Metadata and provenance for an evaluation dataset."""
    dataset_name: str = Field(..., description="Formal dataset title")
    source: str = Field(..., description="Biomedical upstream source attribution")
    version: str = Field(..., description="Dataset version tag")
    retrieval_date: str = Field(..., description="Retrieval date (YYYY-MM-DD)")
    total_samples: int = Field(..., description="Total sample cohort count")
    feature_dimension: int = Field(..., description="Feature vector dimension")
    feature_version: str = Field(..., description="Feature schema version")
    split_strategy: str = Field(..., description="Description of train/val/test splitting strategy")
    supported_ground_truth_organs: List[str] = Field(default_factory=list, description="Organs with validated ground truth labels")
    exploratory_mapping_organs: List[str] = Field(default_factory=list, description="Organs with heuristic evidence mapping")
    description: str = Field(..., description="Detailed dataset description")


class ModelMetricsModel(BaseModel):
    """Classification performance metrics computed on isolated test sets."""
    accuracy: float = Field(..., ge=0.0, le=1.0)
    precision: float = Field(..., ge=0.0, le=1.0)
    recall: float = Field(..., ge=0.0, le=1.0)
    f1_score: float = Field(..., ge=0.0, le=1.0)
    roc_auc: float = Field(..., ge=0.0, le=1.0)
    pr_auc: float = Field(..., ge=0.0, le=1.0)
    brier_score: float = Field(..., ge=0.0, le=1.0)
    confusion_matrix: Dict[str, int] = Field(..., description="Confusion matrix (tp, tn, fp, fn)")


class ModelEvaluationSummary(BaseModel):
    """Evaluation summary for a single baseline model architecture."""
    model_name: str = Field(..., description="Model architecture title")
    model_version: str = Field(..., description="Model version tag")
    architecture: str = Field(..., description="Formal classifier specification")
    metrics: ModelMetricsModel = Field(..., description="Computed validation metrics on test split")


class ExplainabilityEvaluationMetrics(BaseModel):
    """Quality and completeness evaluation of the explainability layer."""
    total_test_predictions_explained: int = Field(..., description="Count of explained test instances")
    explanation_completeness_rate: float = Field(..., ge=0.0, le=1.0, description="Completeness of feature attributions")
    feature_attribution_method: str = Field(..., description="Attribution framework (SHAP)")
    evidence_linkage_coverage: float = Field(..., ge=0.0, le=1.0, description="Fraction of test cases with linked KG paths")
    evidence_sufficiency_rate: float = Field(..., ge=0.0, le=1.0, description="Fraction of test cases passing gating sufficiency")
    causality_distinction: str = Field(..., description="Scope boundary disclaimer")


class EvaluationReportResponse(BaseModel):
    """Full research evaluation report for PharmaTwin risk models."""
    report_id: str = Field(..., description="Unique evaluation report identifier")
    dataset_metadata: EvaluationDatasetMetadata = Field(..., description="Dataset provenance and schema")
    split_type: str = Field(..., description="Split strategy: 'random' or 'temporal'")
    test_sample_count: int = Field(..., description="Number of evaluated test instances")
    positive_sample_count: int = Field(..., description="Number of positive toxicity cases in test set")
    negative_sample_count: int = Field(..., description="Number of negative non-toxic cases in test set")
    models: Dict[str, ModelEvaluationSummary] = Field(..., description="Evaluation results for evaluated baseline models")
    organ_level_evaluation: Dict[str, Any] = Field(..., description="Organ-specific ground truth vs prototype evaluations")
    explainability_evaluation: ExplainabilityEvaluationMetrics = Field(..., description="Explainability and evidence coverage metrics")
    disclaimer: str = Field(
        default=(
            "Research-grade evaluation report. All metrics are computed strictly on isolated test sets. "
            "Not a clinical diagnostic validation or regulatory efficacy certificate."
        ),
        description="Mandatory scientific boundary disclaimer",
    )
    created_at: str = Field(..., description="ISO 8601 UTC timestamp")



