from __future__ import annotations

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


# ---------------------------------------------------------
# Drug Input Schemas
# ---------------------------------------------------------

class DrugSmilesInput(BaseModel):
    """
    Request body for SMILES-based drug analysis.
    """
    smiles: str = Field(
        ...,
        min_length=1,
        description="Drug molecule represented as a SMILES string.",
        examples=["CC(=O)NC1=CC=C(O)C=C1"],
    )
    drug_id: Optional[str] = Field(
        default=None,
        description="Optional drug identifier (e.g., CHEMBL ID, DrugBank ID, or internal code).",
        examples=["CHEMBL112"],
    )
    name: Optional[str] = Field(
        default=None,
        description="Optional common or brand name for the compound.",
        examples=["Acetaminophen"],
    )


# ---------------------------------------------------------
# Nested Molecular Evidence Schemas
# ---------------------------------------------------------

class DrugInputMetadata(BaseModel):
    """Metadata describing the input source and identifiers."""
    drug_id: Optional[str] = Field(default=None, description="Drug or compound identifier")
    name: Optional[str] = Field(default=None, description="Common name of the compound")
    input_type: str = Field(..., description="Format of the input provided ('smiles', 'sdf', 'mol')")
    input_value: Optional[str] = Field(default=None, description="Raw input text or uploaded filename")


class MoleculeIdentifiers(BaseModel):
    """Standardized chemical identifiers and formula properties."""
    canonical_smiles: str = Field(..., description="Canonical SMILES representation generated by RDKit")
    inchi: Optional[str] = Field(default=None, description="IUPAC International Chemical Identifier (InChI)")
    inchi_key: Optional[str] = Field(default=None, description="Standard 27-character hashed InChIKey")
    formula: Optional[str] = Field(default=None, description="Hill system molecular formula (e.g. C8H9NO2)")
    num_atoms: int = Field(..., description="Total atom count (including implicit and explicit hydrogens)")
    num_heavy_atoms: int = Field(..., description="Total count of non-hydrogen heavy atoms")


class MolecularDescriptors(BaseModel):
    """Calculated 2D/3D physicochemical molecular descriptors."""
    molecular_weight: float = Field(..., description="Molecular weight (g/mol)")
    logp: float = Field(..., description="Wildman-Crippen calculated partition coefficient (LogP)")
    tpsa: float = Field(..., description="Topological Polar Surface Area (Å²)")
    hbd: int = Field(..., description="Number of Hydrogen Bond Donors (Lipinski rule)")
    hba: int = Field(..., description="Number of Hydrogen Bond Acceptors (Lipinski rule)")
    rotatable_bonds: int = Field(..., description="Number of rotatable single bonds")
    heavy_atom_count: int = Field(..., description="Total heavy (non-H) atoms")
    ring_count: int = Field(..., description="Total number of rings")
    aromatic_ring_count: int = Field(..., description="Total number of aromatic rings")


class FingerprintData(BaseModel):
    """Morgan circular fingerprint representation."""
    type: str = Field(default="Morgan", description="Fingerprint algorithm type")
    radius: int = Field(default=2, description="Morgan circular radius (equivalent to ECFP4)")
    size: int = Field(default=2048, description="Bit vector length")
    active_bits: int = Field(..., description="Count of active (1) bits")
    bits: List[int] = Field(..., description="2048-element bit vector (0/1 values)")


class ProcessingStatus(BaseModel):
    """Processing health and validation status."""
    valid: bool = Field(default=True, description="Whether the molecular structure is chemically valid")
    message: str = Field(
        default="Molecular evidence extracted successfully.",
        description="Informative status message",
    )


# ---------------------------------------------------------
# Standard API Response Models
# ---------------------------------------------------------

class MolecularProcessingResponse(BaseModel):
    """
    Standard Phase 1 Molecular Evidence Response containing:
    - drug metadata
    - standardized molecule identifiers (canonical SMILES, InChI, InChIKey)
    - 9 physicochemical descriptors
    - 2048-bit Morgan fingerprint
    - validation status
    """
    drug: DrugInputMetadata
    molecule: MoleculeIdentifiers
    descriptors: MolecularDescriptors
    fingerprint: FingerprintData
    status: ProcessingStatus

    # Top-level backward compatibility convenience fields
    valid: bool
    canonical_smiles: str
    input_smiles: Optional[str] = None
    fingerprint_size: int
    active_fingerprint_bits: int
    filename: Optional[str] = None
    svg_image: Optional[str] = None


class DemoDrugItem(BaseModel):
    """Demo compound pre-loaded for quick evaluation."""
    name: str
    smiles: str
    chembl_id: Optional[str] = None
    description: Optional[str] = None


class HealthResponse(BaseModel):
    """API health check response."""
    status: str = "ok"
    app_name: str
    version: str
    environment: str
